version: "3.4"

services:
    api:
        build:
          context: .
          dockerfile: Dockerfile

        ports:
          - "8080:80"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        volumes:
          - "./data/:/var/opt/mssql/data/"
          - "./log/:/var/opt/mssql/log/"
          - "./secrets/:/var/opt/mssql/secrets/"

        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "Teamkill@2017"
            ACCEPT_EULA: "Y"